ali:
  appId: "2021004101631146"
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQClenK/wddRy6t/uiL4BKoBjrdxO6mQWBUJHEMqPJ0GEiM3HO6zP+N+Ssrfh4rD3ggOnNSrmzCUNAKrMpiffumhBGWsJreAM0zESvCozR2djuZVNHs+TgVHQFBLrEJtJhwUubgLyKPZCM9BM/If4mJTQfCD+/jYBGowQCjkywoDBBjvJR1WZibX4bR06Lm5YoPw+DZKbWDVnT9NPurZ1Ke0wewMwvSBoymLiu3E123LudWR57i3Dc7ZZtEwCrDH6mu+q/VOUFW3n43KfxiUMDLsTDJT676xN5De5eoyOJB4CbgYfbsmiXzddhxAVxq/iJy8k0kDvYjzvKWsph3JmUlhAgMBAAECggEABwMGQ7vZ/NxNew8PFkVUUtaSTVkC2VvyID2zVuHUoYI5PcebEbteT2ap7AjZR21sF/prRI5B47XEey6cqv18ttbx2/aUBfmmghbO1chDPf7lIa0kn8I8lQVTobE961QXEoXAF7e7waGO7qtd0h4MnoyHvX/6zmR5f2voj7FOzkvXtOp/seLxWdZVRQpn7KdUZJeHMlaDkqyVvWz0bVQ4OgtdBATXgBbIoP0jMDZj6LAuIYG0mZqyF4DOKKVUcLs9Byr1iG0b5gQIGR/8y6VdjAX6xqJWG0c2hyM5suwqeoTeB1h+8d0LOyBq/TpNSLqpLitCrVwIhmYZ2nS5CFSkMQKBgQDQcq0nnz8CoWPrzr2EndPxUKgETG8bAkwJz4qekdRIfcjNoKdpH/3g+v+PfwU3l+PaOp6kQ6DEDkFw+BZJnxwByyFvNZ/AczHIDUGaKDf7lixh7tzZ+o10C6OxDA3ukPASmInU+ZdSS+avO41hufSda8IpWPoeJ/yLTZVuKrrKJQKBgQDLOlo4PPKqdKdZh96asN/gWJmYPRM1B8GjMPEP35ZmMk83ACvQQCfvz4djT4ocebRZxKIHhC0vdxT/eVyQoyqfMoFVM9NOpDdfTmzK4Kl4wKR86Pc5vpAiUvVykTTrlpcPlgdqbdiHqRmaCb07ADyFdjQlO7TFMLp02LKE7wI3jQKBgQDOz1gYnZiohXNbu+ywLN7g50MrsKHzTB4hBbbkiI7ztUiLKz+tvz3l/2Ga/00v0RURqWNIWoigu/wVly6VsLTa2qy7Z5quGBxl/TD/P7P7ew1hxNl9s2awofOwbuNLtKVb7deiZFfMIN4pMY6eTR7zKLykxVCypr2bgEgn22EjuQKBgQCD0aSlZ7sLH0FRTFTyR5nfPfjai3sC4bYS8PLble5K+YTyKvVATezZmuW5X+U4lSSLOYTTlUNtzzLahtCorH0/55WGO2hrUQ7tjcP5UAH85g+LSdzaIqYA7YhxOIh36ySuomTK/tb9H40QohKQy5V2B/bI09JsOTAoDEq2+QSaHQKBgQCbzwDyKx9OSukYbwxbdlzmlN0lkYRbB1wYFjwCvawqpn5/7LSV7rIv1KzHNPJp73IVlMgP6LOnvIqFFNhreiMTe87UfOhswW7fJs1hUEYV8F8o5defqxtS8dAUHvaFS/fZ6/eR+nLlGtGBfj4O4wgksjMRMvHUzWhqZwzVUEqT4Q==
  aliPublicKey:
  payNotifyURL: https://api.ruiruicaikuai.com/api/ali/aliNotify
aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
autocode:
  transfer-restart: true
  root: D:\project\clothing
  server: /server
  server-api: /api/v1/%s
  server-plug: /plugin/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  s3-force-path-style: false
  disable-ssl: false
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600
cors:
  mode: allow-all
  whitelist:
  - allow-origin: example1.com
    allow-methods: POST, GET
    allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
  - allow-origin: example2.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
db-list:
- disable: true
  type: ""
  alias-name: ""
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
douyin:
  key: ""
  secret: ""
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
excel:
  dir: ./resource/excel/
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  signing-key: b84badd0-4e04-4ee9-a914-a38116489b6a
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
local:
  path: uploads/file
  store-path: uploads/file
mssql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
mysql:
  path: 8.134.131.67
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: clothing
  username: root
  password: local123
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
oracle:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
  prefix: ""
system:
  env: public
  addr: 8889
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
  router-prefix: ""
  host: ""
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
timer:
  start: true
  spec: '@daily'
  with_seconds: false
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
  - tableName: jwt_blacklists
    compareField: created_at
    interval: 168h
txcloud:
  secretId: ""
  secretKey: ""
  smsSdkAppId: ""
  smsSign: ""
  smsTemplate: ""
wechat:
  appID: "wx3ae5179266ede20f"
  appSecret: "d6bb8d192726c6e8f4ea1c2c3cc45065"
  mchID: ""
  mchCertificateSerialNumber: ""
  mchAPIv3Key: ""
  mchAPIv2Key: ""
  payNotifyUrl: ""
  refundNotifyUrl: ""
  getAccessTokenAccount: 0
  miniprogramState: ""
zap:
  level: info
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true
