apiVersion: v1
kind: Service
metadata:
  name: gin-vue-admin-service
  annotations:
    kubesphere.io/description: gin-vue-admin service
  labels:
    app: gin-vue-admin-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gin-vue-admin-fe
