version: "3"

name: gin-vue-admin

volumes:
  mysql:
  redis:

services:
  web:
    build:
      context: ../../web
    image: registry.cn-hangzhou.aliyuncs.com/gva/web
    container_name: gva-web
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - server

  server:
    build:
      context: ../../server
    image: registry.cn-hangzhou.aliyuncs.com/gva/server
    container_name: gva-server
    restart: unless-stopped
    ports:
      - 8888:8888
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: gva-mysql # web初始化：主机名称
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-gva} # web初始化：数据库的名称
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root} # web初始化：root密码
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:6-alpine
    container_name: gva-redis
    restart: unless-stopped
    ports:
      - 16379:6379
    volumes:
      - redis:/data
