name: Docker-CICD
on:
  push:
    branches: [make]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
        go-version: ['1.16']
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
      - name: Sed Config
        shell: bash
        run: |
          sed -i "s#make build-web-local#build-web-local-action#g" Makefile
          sed -i "s#make build-server-local#build-serer-local-action#g" Makefile
          sed -i "s#https://demo.gin-vue-admin.com#http://127.0.0.1#g" web/.env.production
          sed -i 's/${basePath}:${basePort}/${basePath}/g' web/src/view/systemTools/formCreate/index.vue
          make images
          docker push registry.cn-hangzhou.aliyuncs.com/tscuite/gva:v1
