name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Sed Config
          shell: bash
          run: |
            git branch 
            ls -l
        - name: use Node.js 16
          uses: actions/setup-node@v2.1.2
          with:
            node-version: '16.x'
        - name: Build-vue
          run: |
            cd web/ && yarn install && yarn run build
        - name: Set up Go 1.16
          uses: actions/setup-go@v1
          with:
            go-version: 1.16
        - name: Build-go
          run: |
              cd server/ && go mod tidy && go build && mv server ../web/dist/ && cd ../web/dist/ && ls -s 
        - name: scp-centos
          env:
            KEY: ${{ secrets.KEY }}
            HOST: ${{ secrets.Host }}
            USER: ${{ secrets.USER }}
            PROT: ${{ secrets.PROT }}
            MKDIR: ${{ secrets.MKDIR }}
          run: |
            mkdir -p ~/.ssh/ && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
        - name: scp-scp-centos2
          env:
            HOST: ${{ secrets.Host }}
            USER: ${{ secrets.USER }}
            PROT: ${{ secrets.PROT }}
            MKDIR: ${{ secrets.MKDIR }}
          run: |
            scp -P ${PROT} -o StrictHostKeyChecking=no -r web/dist/* ${USER}@${HOST}:${MKDIR}
            ssh -p ${PROT} -o StrictHostKeyChecking=no ${USER}@${HOST} "touch ${MKDIR}test.txt"
              
