name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Sed Config Base
          shell: bash
          run: |
            ls -l

        - name: use Node.js 16
          uses: actions/setup-node@v2.1.2
          with:
            node-version: '16.x'

        - name: Build-vue
          run: |
            cd web/ && yarn install && yarn run build

        - name: Set up Go 1.16
          uses: actions/setup-go@v1
          with:
            go-version: 1.16
            
        - name: Buildgo
          run: |
              cd server/ && go mod tidy && go build && mv server ../web/dist/ && cd ../web/dist/ && ls -s 
